SignatureRequestHandler usage and other
BROKLab/brreg-forvalt pull request #46
Opened 2021-11-25 12:49 UTC by aridder

This PR is trying to illustrate how to use signatureRequestHandler.

Also did an effort to give a clearer message to user when signing is needed in Symfoni ID. Look image below.

![CleanShot 2021-11-25 at 13 46 23](https://user-images.githubusercontent.com/30861967/143444428-5082ffe2-01f8-4859-86ce-175d190cfdb8.png)

2021-12-01 14:01 UTC, Arxcis requested changes
Well played @aridder 👍 I would love to go through this together with you in person, when you have time for it 😉

2021-12-01 14:01 UTC, Arxcis commented on package.json
> +    "neverthrow": "^4.3.1",
👀 New dep

2021-12-01 14:01 UTC, Arxcis commented on src/App.tsx
> +                                <SignatureRequestModal />
Commented out  `{/* <VerifiablePresentationRequestSwitch /> */}` and added `<SignatureRequestModal />`

2021-12-01 14:01 UTC, Arxcis commented on src/App.tsx
> +function VerifiablePresentationRequestSwitch() {
Remember to delete this.

2021-12-01 14:01 UTC, Arxcis commented on src/context/useSymfoni.ts
> +    const signAccessVP = async () => {
I think we should make a new hook for the sign-functions called `useSignatureRequests()`.

- `useSymfoni()` is already complicated enough.
- There is a clear separation of responsibility to be made. Maintaining the connection with Symfoni could be the responsibility of `useSymfoni()`. 
- Making requests over said connection could be the responsibility of a the new proposed `useSignatureRequests()`-hook.

2021-12-01 14:01 UTC, Arxcis commented on src/utils/SignerRequestHandler.ts
> +    async resultsNT<T>() {
This looks like dead code to me. Is it? Maybe there is some magic happening with the new package "neverthrow"

2021-12-01 14:09 UTC, Arxcis requested changes
**Error message**
Unhandled Rejection (Error): Session not approved

**To reproduce**
- Koble fra
- Koble til med Staging appen
- Vent på "Unhandled rejection"

**Demo**

<img src="https://user-images.githubusercontent.com/3092618/144249478-4d70dbc0-c356-4e79-978e-2fe3e7333fe5.gif" width="600"/>

2021-12-01 14:37 UTC, aridder commented on src/context/useSymfoni.ts
> +    const signAccessVP = async () => {
Enig. Kan du hjelpe med dette @Arxcis ? 😇

2021-12-01 14:48 UTC, Arxcis commented on src/App.tsx
> +function VerifiablePresentationRequestSwitch() {
Remembered to delete it in 4ef6c75. Please review @aridder

2021-12-01 14:49 UTC, Arxcis commented on src/context/useSymfoni.ts
> +    const signAccessVP = async () => {
Fix klar i 3eb42e4. Please review @aridder 🙏

2021-12-02 09:14 UTC, aridder commented on src/context/useSymfoni.ts
> +    const signAccessVP = async () => {
Supert 😄

2021-12-02 09:20 UTC, Arxcis requested changes
**BUG**: To "koble til"-vinduer åpnes oppå hverandre på "Opprett aksjeeierbok"-skjermen
<img width="1348" alt="Screenshot 2021-12-02 at 10 19 26" src="https://user-images.githubusercontent.com/3092618/144393391-e4fd2701-f3b7-4f2b-982f-bf6703d734fe.png">

2021-12-02 11:32 UTC, Arxcis requested changes
**FIXED!**

2021-12-02 13:55 UTC, merged